fragment ProductParts on Product {
  __typename
  title
  description
  price
  originalPrice
  affiliateLink
  image
  category
  badge
  rating
  reviewCount
  featured
  publishedAt
}

fragment BlogParts on Blog {
  __typename
  title
  date
  coverImage
  excerpt
  body
}
